### PR TITLE
Compiles to TinyML model; Completes #38

### PR DESCRIPTION
**Pull request by ArttuLe**

### CODE REVIEW

**Comment by ArttuLe** [comment]
Don't know what I did since the #67 commits are seen here. :D

**Comment by doyu** [comment]
Don't you just need a PR against the latest tree?

**Comment by doyu** [comment]
Should we update or ignore this file, "tflm_hello_world/_modidx.py"? It's still complained?

**Comment by ArttuLe** [comment]
Completes #71 #67.

**Comment by ArttuLe** [comment]
Would be good to have some kind of documentation etc. about the nbdev and which of the generated files are necessary to have in the repo and which are not, in order to avoid unnecessary conflicts?

**Comment by ArttuLe** [comment]
@lifeofborna Can any of the nbdev generated files inside /tflm_hello/world be added to .gitignore?

**Comment by ArttuLe** [comment]
Fails because of matplotlib missing, but matplotlib is added as an dependency in this PR

**Comment by doyu** [comment]
Shouldn't it be in setting.ini file?

**Comment by ArttuLe** [comment]
@lifeofborna ?

> Shouldn't it be in setting.ini file?

**Comment by doyu** [comment]
IIRC, depending python packages should be listed in "setting.ini" file ( required?) under nbdev framework?

**Review by doyu — APPROVED** [review]

**Comment by ArttuLe** [comment]
Finally ready for merge :) @doyu

**Review by doyu — APPROVED** [review]

**Pull request merged**
