### PR TITLE
Add unit test code coverage for *.ipynb files with nbdev

### PR DESCRIPTION
**Pull request by lifeofborna**
Added 01_export.ipynb which exports files to python test files. 

(For test purposes we added a test to 00_core. When 01_export.ipynb is ran it will create a python test file under tests folder in nbs. Which will then be ran by pytest.)

### CODE REVIEW

**Comment by doyu** [comment]
Would it be possible to clean this PR?
- no checkpoint / cache changes
-  against the latest tree

The rest looks ok. With the above I'll merge. Thanks!

**Comment by doyu** [comment]
Looking at 01_export, I thought that `procs` itself should be a class, but you seems to have fixed different way (inheritance). Would it be possible to explain a little bit more ?

**Comment by lifeofborna** [comment]
> procs

Yes, I checked Jeremy's tip on how he uses the begin function on the file he told us. There was an example where he did quite the same thing but for warnings. 

 So I implement the same thing for our purpose. I also saw that the process class in nbdev also checks for the begin function in def _proc. 

So I set the preprocs attribute of nb to insert_warning which means that the insert_warning will be run as a pre-processing step before the main processing of nb actually begins.

**Comment by doyu** [comment]
Instead of dumping with xxd, can't just c-program read a binary file of flatbuff tflite directly?

**Pull request closed without merging**
