### PR TITLE
Dummy download tgz, untar tgz into folder, show untarred images in li…

### PR DESCRIPTION
**Pull request by 2laJ2**
…st, choose images

(Webapp chooses image dataset from list #53)

PLEASE NOTE MY COMMENT ON THIS COMMIT:

1.    Download and save here the file stanford-cars.tgz from https://jovian.com/outlink?url=https%3A%2F%2Fs3.amazonaws.com%2Ffast-ai-imageclas%2Fstanford-cars.tgz
 2.   Remove 13.png
3.    Run the app

Because the stanford-cars.tgz file size is close to 2 GB and Github does not allow big files on public repos:
https://github.com/git-lfs/git-lfs/issues/1906

### CODE REVIEW

**Comment by doyu** [comment]
@nellatuulikki can this be located on se?

**Comment by doyu** [comment]
@nellatuulikki can this be located on s3?

**Comment by FexbYk23** [comment]
@doyu Do we really need compression for the datasets? Seems like it would make modifying the dataset really slow since you would have to
1. Download the whole dataset
2. Unpack
3. Modify
4. Repack
5. Upload whole dataset

**Comment by doyu** [comment]
Not necessarily right now.

If we support multiple datasets and also existing ones, compressed archives are easier to handle.

We could skip compression.

**Comment by doyu** [comment]
Do we really need downloading? Can't we use s3 as fs?

**Comment by FexbYk23** [comment]
> Can't we use s3 as fs directly?

I don't think that we can, at least not with boto3.

**Comment by 2laJ2** [comment]
We could also make a new task that suitable amount of these car pics (around 500) is taken from this dataset and used to make a small dataset, which is then compressed and put into s3 or somewhere. The thing is, that the available datasets are all compressed, so at some point the decompression/compression has to be done anyway. But there's no need to use a huge dataset of this size, we could make a small one just for our purposes. Then we could customize the internal folder structure of the dataset and the downloading/decompression code. At this moment, the code fits only to the folder structure of stanford-cars.tgz. The internal folder structure of different datasets available also seems to have some variation.

**Comment by doyu** [comment]
> But the actual problem is that the tgz file is so huge, 2 MB, that the localhost app couldn't manage the downloading from web.

Can we survive skipping compression just for now, keeping dir structure in S3?

**Pull request closed without merging**
