### PR TITLE
WebApp observes & show Hello prediction at realtime

### PR DESCRIPTION
**Pull request by FexbYk23**
I made the Web app show values from the helloworld. #13

### CODE REVIEW

**Review by doyu — COMMENTED** [review]
Looks good to me.
A few notes. nbdev will take care of unit test & document at once. You may want to consider to facter out non-UI part in a pacakge as this, https://nbdev.fast.ai/tutorials/tutorial.html . Then you wouldn't need to write document in README.md

Another thing is that, TCP server is just temporary solution. In Sprint 2 this would receieve a image file. TCP server would need to take care of cutting a file out from a strream. I may consider some REST PUT might be easier to handle. Any better idea?

I won't pull this until Arttu's is merged. Thank you for your good work!

**Comment by doyu** [comment]
A new PR merged. So closing this now

**Comment by doyu** [comment]
misunderstood :P

**Comment by doyu** [comment]
Previously I implemented with LwM2M (CoAP over UDP), but this kind of connection management rather belongs to IoT platform. In principle, TinyMLaaS could be intergrated on the top of IoT platform. In this implemntation, we just have to pretend having some thin IoT platform in it. IoT platform here means mainly "Device management" & "Data management". In this implementation, we assume that there should be some bridging relay server between TinyMLaaS and a device if a device cannot send data directly to TinyMLaaS. And this bridging relay server should be enough powerful to have some TCP connections. A device just needs to upload a image data. So I was thinking just using REST PUT for uploading a file would be enough simple without much unnecessary implementation here? In my opinion, just picking up one IoT protocol (MQTT) here may not make much sense?

@robertmora may have some comments here.

**Comment by FexbYk23** [comment]
> Looks good to me. A few notes. nbdev will take care of unit test & document at once. You may want to consider to facter out non-UI part in a pacakge as this, https://nbdev.fast.ai/tutorials/tutorial.html . Then you wouldn't need to write document in README.md
> 
> Another thing is that, TCP server is just temporary solution. In Sprint 2 this would receieve a image file. TCP server would need to take care of cutting a file out from a strream. I may consider some REST PUT might be easier to handle. Any better idea?
> 
> I won't pull this until Arttu's is merged. Thank you for your good work!

I rewrote the TCP code as a Jupyter Notebook, as it was basically the only non-UI part.

I'm not sure if I did it correctly but for now it seems that you need to manually convert the notebook by running `nbdev_export`

**Comment by doyu** [comment]
`nbdev_prepare` runs needed scripts. As explained in the video, you are prompted to write tests & doc in the jupyter notebook, which would be automatically converted into the appropriate places.

**Comment by doyu** [comment]
@FexbYk23 Seems conflicting now. Please fix this conflict first! If nbdev_prepare update is included, I'll merge this PR. Thanks!

**Comment by doyu** [comment]
@FexbYk23 the above says conflicting? Could you make a PR against the top of tree again?

**Review by doyu — APPROVED** [review]
LGTM

**Pull request merged**
