### PR TITLE
Research on relevant UI / Services (Edge Impulse, Arduino, mbed, IFTTT and Sony MESH etc.)#14

### PR DESCRIPTION
**Pull request by 2laJ2**
Fixed the Workflow permissions, now the CI passes. I'm sorry for all the extra work I'm causing with messing up with GitHub and doing extra PR.

So, according to this limited search, the Arduino board, perhaps with Wiring, could be a good choice, since they support Linux, Mac and Windows. Arduino has a large community of users and a good product range. The choice of cloud service depends on the project needs.

### CODE REVIEW

**Comment by 2laJ2** [comment]
Seems like Github added the task #53 file into this other PR. So now there's two files to check.

**Comment by doyu** [comment]
Pending on @tastingmusic 's review now. He's on vacation this week. He'll review once he's back from the holiday, in a week?

**Comment by doyu** [comment]
@2laJ2 This includes unrelated changes, https://github.com/Origami-TinyML/tflm_hello_world/pull/73/files
Please strip down and send a PR with only necessary one again. Thanks!

**Comment by 2laJ2** [comment]
Every single commit to my Github repo in the cloud ends up into this PR automatically, if I try to make a new PR. Github doesn't let me open a different PR. That is how Github works. If somebody knows how to do it exactly the way that you suggest, I'm happy to learn how.

So is it then so, that I should not pull from the main repo and check that the changes I have made will also work with the current main repo before making the commit and PR?

**Comment by doyu** [comment]
@2laJ2 you could try `git rebase` or `git rebase --onto origin/main`

**Comment by 2laJ2** [comment]
I checked the wanted commit with git log and then followed these instructions:
https://stackoverflow.com/questions/448919/how-can-i-remove-a-commit-on-github

As long as this PR is open, every commit I push to my own repo (in the cloud) will end up in this PR. For example, this last commit. I did not make a PR.

**Comment by doyu** [comment]
For convenience, I'm merging tihs for now since I don't want to have PR pending for long here.

@tastingmusic should reivew as soon as he's back on GH issue comments.

**Pull request merged**
