### PR TITLE
Integrate Python tests inGithub workflow

### PR DESCRIPTION
**Pull request by matiasto**
I'll open this PR for you to consult me on nbdev problem. In my fork, I had a problem where nbdev failed in CI for some reason.

### CODE REVIEW

**Comment by matiasto** [comment]
Shouldn't this be then included in Build, i.e. Dockerfile?

**Comment by doyu** [comment]
Probably you could do with nbdev_install_hooks alternatively???

nbdev_prepare will generate / update files so that you need to explicitly submit them in the git repo before a PR.

**Comment by tolppama** [comment]
I did not completely understand your previous message. Nevertheless, I've been trying all kinds of tricks but can't get it to complete. It always fails on:
```yml
- name: Use nbdev-ci workflow
      uses: fastai/workflows/nbdev-ci@master
```

Would you happen to have any advice?

**Comment by doyu** [comment]
@lifeofborna can you help here?

**Comment by lifeofborna** [comment]
> @lifeofborna can you help here?

sure we'll talk with matias about it

**Pull request closed without merging**
