### PR TITLE
CI test coverage #16

### PR DESCRIPTION
**Pull request by ArttuLe**
CI passes, but Codecov uploader doesn't find files needed. The .gcov files are copied from the container into host machine. "There was an error running the uploader: No gcov files found"

### CODE REVIEW

**Comment by doyu** [comment]
@ArttuLe I'll take a look later. For the mean while, try to look for some help in Discord! Building up a culture to help each other is also important in a team ;)

**Comment by doyu** [comment]
@ArttuLe Did you actually make the following work?
https://about.codecov.io/blog/how-to-set-up-codecov-with-c-and-github-actions/

I tried another one, and it work OK.
https://github.com/shenxianpeng/gcov-example

Can you try to integrate this one, instead?

**Comment by ArttuLe** [comment]
Yes, made it work, but CodeCov doesn't somehow get the reports. I'll try integrating the link you provided if that works better.

**Comment by doyu** [comment]
Even codecov example doesn't work for me. Did I miss something here?

https://asciinema.org/a/553880

**Pull request merged**
