### PR TITLE
Revert "fix: try to get run python coverage on yml file to work with CI."

### PR DESCRIPTION
**Pull request by lifeofborna**
Reverts Origami-TinyML/tflm_hello_world#76

We are still speculating on this issue with @matiasto . So for now its better to revert the changes. We will make a new PR when its ready.

### CODE REVIEW

**Comment by lifeofborna** [comment]
Seems like there is something wrong with the workflow and nbdev. I think this issue should be further investigated.

**Comment by lifeofborna** [comment]
It seems like this commit has been approved: 

https://github.com/Origami-TinyML/tflm_hello_world/commit/a84bf006443fb66db84c95520c8339fe21c428f3

Which may cause the issues nbdev CI issues. It may have some broken code inside it.

**Comment by matiasto** [comment]
@doyu I think the best course of action is to revert to 14 February. 
SHA: 68360fa660a21050cc51a62a619e6f7e5e180c57

We would only have to add Nellas' meeting notes again.

**Comment by doyu** [comment]
Done

@nellatuulikki please send your PR again for the TOT.

**Pull request closed without merging**
